#!/bin/bash
#
# Install / upgrade pip
# Install modules needed to run cm-lite-daemon
#

if which pip > /dev/null; then
  echo "pip found"
else
  if which yum > /dev/null; then
    yum install python-pip
  elif which apt > /dev/null; then
    apt install python-pip
  else
    echo "Unable to install pip"
    exit 1
  fi
fi

pip install --upgrade pip
pip install -rrequirements.txt
